### ISSUE TITLE
ValueError: Could not find a backend to open data/irrmaps/aerodynamics_workshop_2k.hdr with iomode ri.

### ISSUE THREAD

**Issue by andrewyguo** [NVlabs/nvdiffrec#105]
I am getting this when I run: 

```
python train.py  --config configs/bob.json 
```

This is the full error log: 

```
~/nvdiffrec$ python train.py  --config configs/bob.json 
Config / Flags:
---------
config configs/bob.json
iter 1000
batch 4
spp 1
layers 1
train_res [512, 512]
display_res [512, 512]
texture_res [1024, 1024]
display_interval 0
save_interval 100
learning_rate [0.03, 0.003]
min_roughness 0.08
custom_mip False
random_textures True
background white
loss logl1
out_dir out/bob
ref_mesh data/bob/bob_tri.obj
base_mesh None
validate False
mtl_override None
dmtet_grid 64
mesh_scale 2.1
env_scale 2.0
envmap data/irrmaps/aerodynamics_workshop_2k.hdr
display None
camera_space_light False
lock_light False
lock_pos False
sdf_regularizer 0.2
laplace relative
laplace_scale 10000.0
pre_load True
kd_min [0.0, 0.0, 0.0, 0.0]
kd_max [1.0, 1.0, 1.0, 1.0]
ks_min [0, 0.25, 0]
ks_max [1.0, 1.0, 1.0]
nrm_min [-1.0, -1.0, 0.0]
nrm_max [1.0, 1.0, 1.0]
cam_near_far [0.1, 1000.0]
learn_light True
local_rank 0
multi_gpu False
---------
DatasetMesh: ref mesh has 10688 triangles and 5344 vertices
---> WARNING: Picked a texture resolution lower than the reference mesh [1024, 1024] < [2048, 2048]
Traceback (most recent call last):
  File "/home/andrewg/nvdiffrec/train.py", line 563, in <module>
    dataset_train    = DatasetMesh(ref_mesh, glctx, RADIUS, FLAGS, validate=False)
  File "/home/andrewg/nvdiffrec/dataset/dataset_mesh.py", line 46, in __init__
    self.envlight = light.load_env(FLAGS.envmap, scale=FLAGS.env_scale)
  File "/home/andrewg/nvdiffrec/render/light.py", line 141, in load_env
    return _load_env_hdr(fn, scale)
  File "/home/andrewg/nvdiffrec/render/light.py", line 131, in _load_env_hdr
    latlong_img = torch.tensor(util.load_image(fn), dtype=torch.float32, device='cuda')*scale
  File "/home/andrewg/nvdiffrec/render/util.py", line 441, in load_image
    img = load_image_raw(fn)
  File "/home/andrewg/nvdiffrec/render/util.py", line 438, in load_image_raw
    return imageio.imread(fn)
  File "/home/andrewg/miniconda3/envs/dmodel/lib/python3.9/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/home/andrewg/miniconda3/envs/dmodel/lib/python3.9/site-packages/imageio/v2.py", line 226, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/home/andrewg/miniconda3/envs/dmodel/lib/python3.9/site-packages/imageio/core/imopen.py", line 298, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `data/irrmaps/aerodynamics_workshop_2k.hdr`` with iomode `ri`.
```

**Comment by andrewyguo** [comment]
Turns out, I forgot to run: 
```
imageio_download_bin freeimage
```

After running this, I was able to solve my error
