### ISSUE TITLE
Pending after computing MSE and PSNR

### ISSUE THREAD

**Issue by hzhshok** [NVlabs/nvdiffrec#13]
Hello, 
  Recently i made myself test data to practically check what resolution and parameters is suitable for my desktop, i made the resolution of 1264x1264, and last it pended even for 24 hours,  i checked it consumed the approximate 7408g GPU, so, is my data too rough(**MSE** - 0.2591xx, last  **img_loss**=1.109134) or the other reason?  

So, someone give me a share/suggestion about how to do to my high resolution please?   e.g. the relationship, 11g GPU: max resolution and scale.

In addition: actually my images is very high resolution(3000x4000), but to my GPU(3080 11g), i scale that to 1264x1264 after some tries.

**Hardware:** DESKTOP RTX 3080(11g), cuda 11.3.
**Software**: ubuntu20.04
**Running GPU cost during pending**: always fixed cost, approximate 7.xg
**Running output and strace log:** see the following.

**The console output:** 
python3 train.py --config ./configs/nerf_handong.json
Config / Flags:
---------
config ./configs/nerf_handong.json
iter 2000
batch 1
spp 1
layers 4
train_res [1264, 1264]
display_res [1264, 1264]
texture_res [2048, 2048]
display_interval 0
save_interval 100
learning_rate [0.03, 0.01]
min_roughness 0.08
custom_mip False
random_textures True
background white
loss logl1
out_dir out/nerf_handong
ref_mesh data/nerf_synthetic/handong
base_mesh None
validate True
mtl_override None
dmtet_grid 128
mesh_scale 2.75
env_scale 1.0
envmap None
display [{'latlong': True}, {'bsdf': 'kd'}, {'bsdf': 'ks'}, {'bsdf': 'normal'}]
camera_space_light False
lock_light False
lock_pos False
sdf_regularizer 0.2
laplace relative
laplace_scale 3000
pre_load True
kd_min [0.0, 0.0, 0.0, 0.0]
kd_max [1.0, 1.0, 1.0, 1.0]
ks_min [0, 0.1, 0.0]
ks_max [1.0, 1.0, 1.0]
nrm_min [-1.0, -1.0, 0.0]
nrm_max [1.0, 1.0, 1.0]
cam_near_far [0.1, 1000.0]
learn_light True
local_rank 0
multi_gpu False
---------
DatasetNERF: 28 images with shape [1264, 1264]
DatasetNERF: 28 images with shape [1264, 1264]
Encoder output: 32 dims
Using /home/xx/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/xx/.cache/torch_extensions/py38_cu113/renderutils_plugin/build.ninja...
Building extension module renderutils_plugin...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module renderutils_plugin...
iter=    0, img_loss=1.166577, reg_loss=0.334082, lr=0.02999, time=468.3 ms, rem=15.61 m
...
iter= 1990, img_loss=0.936701, reg_loss=0.014961, lr=0.01199, time=484.8 ms, rem=4.85 s
iter= 2000, img_loss=1.109134, reg_loss=0.014806, lr=0.01194, time=503.9 ms, rem=0.00 s
Running validation
**MSE,      PSNR**
0.25911513, 6.480

^C^CKilled

**strace log:** 
sched_yield()                           = 0
sched_yield()                           = 0
sched_yield()                           = 0
...
sched_yield()                           = 0
sched_yield()                           = 0

Thanks for your contribution!

Regards

**Comment by jmunkberg** [comment]
After the first pass, we run xatlas to create a UV parameterization on the triangle mesh. If the first pass failed to create a reasonable mesh, this step can take quite some time or even fail. How does the mesh look in your case at the end of the first pass?

For memory consumption, you can log the usage using `nvidia-smi --query-gpu=memory.used --format=csv -lms 100` when you run to get a feel for the usage. Memory is a function of image resolution, batch size and if you have depth peeling enabled. We ran the results in the paper using HPUs with 32+GB of memory, but  it should run on lower-spec GPUs if you decrease the rendering resolution and/or batch size.

**Comment by hzhshok** [comment]
Thanks @jmunkberg! 

Why i raised this issue is because the general command 'nvidia-smi' without parameters showed it only used 7.4G totally, and that GPU memory has 11G, so i suspected that is not memory issue.

Sorry, once i checked the related output including mesh, but i forgot what output it is, and now that host was destroyed,  so i am only able to continue to track this after making my new environment.

In addition, the GPU system even was made pending(nvidia-smi was blocked, no any response.) every time train.py failed.
I understand why this feature uses Starvation algorithm  for the GPU memory allocation, but, 

Does team have the plan to optimize this feature for it's memory allocation strategy?

Regards

**Comment by hzhshok** [comment]
Hello, 
Now i reproduced this issue although i did not used the same using COLMAP, but everything seems all the prints are the same(the LOG, process running io[sched_yield]). 

From the showed, it should be the memory issue, as you said it failed during UV creation(xatlas_uvmap), i did not do the deep dig to record current showed.

**Result**: No mesh created.

Hardware: DESKTOP RTX 3080(10240MiB), cuda 11.3.
Software: ubuntu20.04
Running GPU cost during pending: always fixed cost, approximate  5638M
Running output and strace log: see the following.

**Console log:**
...
iter= 5000, img_loss=0.841482, reg_loss=0.014437, lr=0.00300, time=270.0 ms, rem=0.00 s
Running validation
MSE, PSNR
0.25911513, 6.480
Running validation
**MSE, PSNR**
0.25911513, 6.480

**Memory monitor:**
$ nvidia-smi --query-gpu=memory.used --format=csv -lms 2000
memory.used [MiB]
5710 MiB
...
5638 MiB

Wed Apr 13 17:53:01 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 30%   37C    P8    20W / 320W |   5638MiB / 10240MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1294      G   /usr/lib/xorg/Xorg                 53MiB |
|    0   N/A  N/A      1827      G   /usr/lib/xorg/Xorg                212MiB |
|    0   N/A  N/A      1962      G   /usr/bin/gnome-shell               67MiB |
|    0   N/A  N/A      2278      G   /usr/lib/firefox/firefox           56MiB |
|    0   N/A  N/A      9387    C+G   python3                          5229MiB |
+-----------------------------------------------------------------------------+

Regards
[Uploading metrics.txt…]()

**Comment by hzhshok** [comment]
Hello, 
Now i reproduced this issue although i did not used the same using COLMAP, but everything seems all the prints are the same(the LOG, process running io[sched_yield]). 

From the showed, it should be the memory issue, as you said it failed during UV creation(xatlas_uvmap), i did not do the deep dig to record current showed.

**Result**: No mesh created.

Hardware: DESKTOP RTX 3080(10240MiB), cuda 11.3.
Software: ubuntu20.04
Running GPU cost during pending: always fixed cost, approximate  5638M
Running output and strace log: see the following.

**Console log:**
...
iter= 5000, img_loss=0.841482, reg_loss=0.014437, lr=0.00300, time=270.0 ms, rem=0.00 s
Running validation
MSE, PSNR
0.25911513, 6.480
Running validation
**MSE, PSNR**
0.25911513, 6.480

**Memory monitor:**
$ nvidia-smi --query-gpu=memory.used --format=csv -lms 2000
memory.used [MiB]
5710 MiB
...
5638 MiB

Wed Apr 13 17:53:01 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 30%   37C    P8    20W / 320W |   5638MiB / 10240MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1294      G   /usr/lib/xorg/Xorg                 53MiB |
|    0   N/A  N/A      1827      G   /usr/lib/xorg/Xorg                212MiB |
|    0   N/A  N/A      1962      G   /usr/bin/gnome-shell               67MiB |
|    0   N/A  N/A      2278      G   /usr/lib/firefox/firefox           56MiB |
|    0   N/A  N/A      9387    C+G   python3                          5229MiB |
+-----------------------------------------------------------------------------+

Regards
[Uploading metrics.txt…]()

**Comment by jmunkberg** [comment]
Hello @hzhshok ,

Looking at the error metrics:

> MSE, PSNR
> 0.25911513, 6.480

That's extremely large errors, so I assume the first pass did not train properly. What does the images look like in the `out/nerf_handong` folder (or the name of your current experiment)? If the reconstruction succeeded, I would expect a PSNR of 25 dB or higher. If the reconstruction fails, it is very hard to create a uv-parameterization (it is hard to uv map a triangle soup), and xatlas would fail/hang. 

I suspect something else is wrong already in the first pass. A few things that can affect quality:

- Is the lighting setup constant in all training data?
- Do you have high quality foreground segmentation masks?
- Are you sure that the poses are correct and that the pose indices and corresponding images match?
- Does the training images contain substantial motion or defocus blur

Also, just to verify, is the example from the readme `python train.py --config configs/bob.json` working without issues on your setup?

**Comment by hzhshok** [comment]
Hello, Thanks @jmunkberg!
Yes, that something should be wrong in the first pass, and i will check the trained effect of the labeled images using current images as the fundamental.

Is the lighting setup constant in all training data?
-- No, some of images has the strong light, because this images is from outdoor.
**Do you have high quality foreground segmentation masks?**
--Do you mean the high quality foreground is that the image was labeled on the pure background as the examples(chair or other...)?
   This time, I just used the wild outdoor images to check if this can be done for non-constant light and  relatively pure color in images, and did not label the images, and i will  check the effect with the high quality foreground.-)
   In addition, i just want to check the effect of texturing mesh after using the traditional sfm tool.
**Are you sure that the poses are correct and that the pose indices and corresponding images match?**
   -- Yes, it should be, the colmap can get result although it did not had good effect.
**Does the training images contain substantial motion or defocus blur**
   -- it no more blur, that images are resized from high resolution 3003x4000 to 1264x1264, i think i should have impact, but 

Regards

**Comment by hzhshok** [comment]
Hello,
    Now i found other samples about building to try this feature, and labeled the samples to eliminate the background, it seems like passing the first train/mesh , but it failed to do second train/mesh, so please give a suggestion,  thanks!

**The question:**
**a.** Why it breaked off during running? the log seeing the console output?
       Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function texture2d_mipBackward returned an invalid gradient at index 0 - got [1, 4, 4, 3] but expected shape compatible with [1, 5, 5, 3]
      Maybe the MSE/PSNR are not the good one, if so,  could you help give me suggestion please about how to imporve training images aspects? or trainning images not suitable the rule？
**b.** Why the result have serious blur? see the intermediate picture and two original image sampels.
c. How to imporve the last result?  input trining images or other. 


![img_dmtet_pass1_000000](https://user-images.githubusercontent.com/52768640/167522418-5a751c27-0a5e-4e15-979b-d25a65c78c48.png)
![img_dmtet_pass1_000041](https://user-images.githubusercontent.com/52768640/167522422-36cc486e-b979-40b3-b6d1-2cf49b141c1a.png)
![img_dmtet_pass1_000045](https://user-images.githubusercontent.com/52768640/167522423-9256a750-21a4-4acb-8c15-0b4e6c875c97.png)
![img_dmtet_pass1_000079](https://user-images.githubusercontent.com/52768640/167522425-5c7919f2-dca2-4803-9b05-e22ed0fc6ea2.png)
![img_dmtet_pass1_000080](https://user-images.githubusercontent.com/52768640/167522428-730e1881-7b3a-41bb-995e-2c4dc215bd85.png)

![IMG_4287](https://user-images.githubusercontent.com/52768640/167522714-de5bef9c-3e2d-442f-be2a-ecf8e9d1ada2.png)
![IMG_4332](https://user-images.githubusercontent.com/52768640/167522790-3181b02a-6f98-4eef-ad86-8c7d284181aa.png)


**Hardware**: 3080(24G) - win11

Samples: (see the attached two picture  for the example)
a. 50 images.
b. Resolution: 2456(width)x1638(hight)
c. Transform parameters with: **--aabb_scale 2** for colmap.

{
    "ref_mesh": "data/nerf_synthetic/building",
    "random_textures": true,
    "iter": 8000,
    "save_interval": 100,
    "texture_res": [5120,5120],
    "train_res": [1638, 2456],
    "batch": 1,
    "learning_rate": [0.03, 0.0001],
    "ks_min" : [0, 0.08, 0.0],
    "dmtet_grid" : 128,
    "mesh_scale" : 5,
    "laplace_scale" : 3000,
    "display": [{"latlong" : true}, {"bsdf" : "kd"}, {"bsdf" : "ks"}, {"bsdf" : "normal"}],
    "layers" : 4,
    "background" : "**white**",
    "out_dir": "nerf_building"
}

**The console log:** 
iter= 8000, img_loss=0.061592, reg_loss=0.016066, lr=0.00075, time=499.0 ms, rem=0.00 s
Running validation
MSE,      PSNR
0.02140407, 17.038
Base mesh has 214359 triangles and 105082 vertices.
Writing mesh:  out/nerf_building\dmtet_mesh/mesh.obj
    writing 105082 vertices
    writing 224020 texcoords
    writing 105082 normals
    writing 214359 faces
Writing material:  out/nerf_building\dmtet_mesh/mesh.mtl
Done exporting mesh
Traceback (most recent call last):
  File "D:\zhansheng\proj\windows\nvdiffrec\train.py", line 620, in <module>
    geometry, mat = optimize_mesh(glctx, geometry, base_mesh.material, lgt, dataset_train, dataset_validate, FLAGS,
  File "D:\zhansheng\proj\windows\nvdiffrec\train.py", line 428, in optimize_mesh
    total_loss.backward()
  File "C:\Users\jinshui\anaconda3\envs\dmodel\lib\site-packages\torch\_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\jinshui\anaconda3\envs\dmodel\lib\site-packages\torch\autograd\__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function texture2d_mipBackward returned an invalid gradient at index 0 - got [1, 4, 4, 3] but expected shape compatible with [1, 5, 5, 3]

Regards

**Comment by jmunkberg** [comment]
That is an error from nvdiffrast. I would try to use power-of-two resolutions on the textures and training, e.g.,
```
    "texture_res": [ 1024, 1024 ],
    "train_res": [1024, 1024],
 ```
 In case the `texture2d_mipBackward` is not stable for all (non-pow2) resolutions.

**Comment by hzhshok** [comment]
@ZirongChan, i am not sure if it is caused by memory, you know i used images near 2kX2k which costed more memory for my single 24G GPU, so I used the strategy of spliting image to small blocks  as Jmunkberg talked inside other issue, at least it did not happen such error.

Regards
