### ISSUE TITLE
Getting stuck during installation

### ISSUE THREAD

**Issue by eliyoom** [NVlabs/nvdiffrec#156]
Hello
The following command runs forever :

**conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge**

Breaking it into several parts works, but then the following line fails:

pip install --global-option="--no-networks" git+https://github.com/NVlabs/tiny-cuda-nn#subdirectory=bindings/torch

As a result, I get the following error when executing       **python train.py --config configs/bob.json**   (tinycudann missing)

Traceback (most recent call last):
  File "C:\Users\eli\Algo_studio\algo_studio\TV_Python\nvdiffrec-main\train.py", line 36, in <module>
    from render import mlptexture
  File "C:\Users\eli\Algo_studio\algo_studio\TV_Python\nvdiffrec-main\render\mlptexture.py", line 11, in <module>
    import tinycudann as tcnn
ModuleNotFoundError: No module named 'tinycudann'

**Comment by jmunkberg** [comment]
Hello @eliyoom ,

For the first remark, this is a standard PyTorch install. https://pytorch.org/get-started/locally/ . You can install through conda or through pip (often slightly faster in my experience) inside the conda env. Note per our instructions that you need to match the CUDA toolkit versions in torch and the one you install to build the extension. 

For the second remark, AFAIU, this is an issue with installing tcnn, so please check there for help: https://github.com/NVlabs/tiny-cuda-nn

**Comment by eliyoom** [comment]
Thank you so much!
It is working now.
