### ISSUE TITLE
 OSError: PyTorch CUDA is unavailable. tinycudann requires PyTorch to be installed with the CUDA backend.

### ISSUE THREAD

**Issue by Xyndra** [NVlabs/nvdiffrec#36]
I am trying to install this on windows(Radeon RX 570, if that matters)
```
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\envs\dmodel\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Sammy_HD\\AppData\\Local\\Temp\\pip-req-build-heecsmjx\\bindings/torch\\setup.py'"'"'; __file__='"'"'C:\\Users\\Sammy_HD\\AppData\\Local\\Temp\\pip-req-build-heecsmjx\\bindings/torch\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Sammy_HD\AppData\Local\Temp\pip-pip-egg-info-4is6wjv_'
         cwd: C:\Users\Sammy_HD\AppData\Local\Temp\pip-req-build-heecsmjx\bindings/torch
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Sammy_HD\AppData\Local\Temp\pip-req-build-heecsmjx\bindings/torch\setup.py", line 115, in <module>
        raise EnvironmentError("PyTorch CUDA is unavailable. tinycudann requires PyTorch to be installed with the CUDA backend.")
    OSError: PyTorch CUDA is unavailable. tinycudann requires PyTorch to be installed with the CUDA backend.
    Building PyTorch extension for tiny-cuda-nn version 1.6
    ----------------------------------------
```
The command I was able to isolate was 
```
pip install --global-option="--no-networks" git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch
```

**Comment by JHnvidia** [comment]
Hi, sorry but this codebase only works with NVIDIA cards. We rely heavily on CUDA and it's not supported on Radeon GPUs.
