### ISSUE TITLE
error: legacy-install-failure

### ISSUE THREAD

**Issue by ishandutta04** [NVlabs/nvdiffrec#60]
I am installing the setup on an EC2 instance with a 16 GB GPU. I tried with VS Studio 16.11 and 16.9.4 but the error persists. 

I get the following error when running the command `pip install --global-option="--no-networks" git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch imageio_download_bin freeimage` on Windows 10:

# Error Log
```
 Error limit reached.
      100 errors detected in the compilation of "C:/Users/Administrator/AppData/Local/Temp/1/pip-req-build-pth07vly/src/common_device.cu".
      Compilation terminated.
      common_device.cu
      [5/5] cl /showIncludes /nologo /O2 /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IC:\Users\Administrator\AppData\Local\Temp\1\pip-req-build-pth07vly/include -IC:\Users\Administrator\AppData\Local\Temp\1\pip-req-build-pth07vly/dependencies -IC:\Users\Administrator\AppData\Local\Temp\1\pip-req-build-pth07vly/dependencies/cutlass/include -IC:\Users\Administrator\AppData\Local\Temp\1\pip-req-build-pth07vly/dependencies/cutlass/tools/util/include -IC:\Users\Administrator\AppData\Local\Temp\1\pip-req-build-pth07vly/dependencies/fmt/include -IC:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\torch\include -IC:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\torch\include\torch\csrc\api\include -IC:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\torch\include\TH -IC:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -IC:\ProgramData\Anaconda3\envs\dmodel\include -IC:\ProgramData\Anaconda3\envs\dmodel\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt" -c C:\Users\Administrator\AppData\Local\Temp\1\pip-req-build-pth07vly\bindings\torch\tinycudann\bindings.cpp /FoC:\Users\Administrator\AppData\Local\Temp\1\pip-req-build-pth07vly\bindings\torch\build\temp.win-amd64-3.9\Release\tinycudann/bindings.obj /std:c++14 -DTCNN_MIN_GPU_ARCH=75 -DFMT_HEADER_ONLY=1 -DTCNN_NO_NETWORKS -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=0
      ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\torch\utils\cpp_extension.py", line 1808, in _run_ninja_build
          subprocess.run(
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

      The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\1\pip-req-build-pth07vly\bindings/torch\setup.py", line 121, in <module>
          setup(
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\command\install.py", line 664, in run
          self.run_command('build')
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\dist.py", line 1214, in run_command
          super().run_command(command)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\torch\utils\cpp_extension.py", line 765, in build_extensions
          build_ext.build_extensions(self)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\command\build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\torch\utils\cpp_extension.py", line 738, in win_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\torch\utils\cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "C:\ProgramData\Anaconda3\envs\dmodel\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> tinycudann

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

Windows: Windows 10
Cuda: 11.6
Visual Studio: Visual Studio 2019 with build tools installed

**Comment by JHnvidia** [comment]
Hi,

As mentioned in the error message the **tinycudann** package failed to install due to compilation errors. There's a few version conflicts between MSVC/CUDA versions that sometimes causes these errors, so I would recommend upgrading both CUDA and visual studio to the very latest versions (and make sure that CUDA_PATH points to the right version). 

There's also an older issue that might give some useful info:
https://github.com/NVlabs/nvdiffrec/issues/46, https://github.com/NVlabs/tiny-cuda-nn/issues/110#issuecomment-1159309395

**Comment by verifiedanswer** [comment]
[[Solved] error: legacy-install-failure](https://verifiedanswer.com/solved-error-legacy-install-failure/)

**Comment by siatheindochinese** [comment]
On Ubuntu 22.04, reverting from gcc-11 and g++-11 to gcc-10 and g++-10 solved this problem for me.
