### ISSUE TITLE
Cannot build nvdiffrast_plugin_gl.so 

### ISSUE THREAD

**Issue by JiyouSeo** [NVlabs/nvdiffrec#76]
Hello, thank you for your great research!

I have a problem running the train code.
I installed following the script in README
~~~
conda create -n dmodel python=3.9
activate dmodel
conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge
pip install ninja imageio PyOpenGL glfw xatlas gdown
pip install git+https://github.com/NVlabs/nvdiffrast/
pip install --global-option="--no-networks" git+https://github.com/NVlabs/tiny-cuda-nn#subdirectory=bindings/torch
imageio_download_bin freeimage
~~~
And it Installed successfully.
But when running the code,
~~~
python train.py --config configs/bob.json
~~~
It return
~~~
Config / Flags:
---------
config configs/bob.json
iter 1000
batch 4
spp 1
layers 1
train_res [512, 512]
display_res [512, 512]
texture_res [1024, 1024]
display_interval 0
save_interval 100
learning_rate [0.03, 0.003]
min_roughness 0.08
custom_mip False
random_textures True
background white
loss logl1
out_dir out/bob
ref_mesh data/bob/bob_tri.obj
base_mesh None
validate False
mtl_override None
dmtet_grid 64
mesh_scale 2.1
env_scale 2.0
envmap data/irrmaps/aerodynamics_workshop_2k.hdr
display None
camera_space_light False
lock_light False
lock_pos False
sdf_regularizer 0.2
laplace relative
laplace_scale 10000.0
pre_load True
kd_min [0.0, 0.0, 0.0, 0.0]
kd_max [1.0, 1.0, 1.0, 1.0]
ks_min [0, 0.25, 0]
ks_max [1.0, 1.0, 1.0]
nrm_min [-1.0, -1.0, 0.0]
nrm_max [1.0, 1.0, 1.0]
cam_near_far [0.1, 1000.0]
learn_light True
local_rank 0
multi_gpu False
---------
Traceback (most recent call last):
  File "/home/jiyouseo/anaconda3/envs/dmodel/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1809, in _run_ninja_build
    subprocess.run(
  File "/home/jiyouseo/anaconda3/envs/dmodel/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jiyouseo/nvdiffrec/train.py", line 556, in <module>
    glctx = dr.RasterizeGLContext()
  File "/home/jiyouseo/anaconda3/envs/dmodel/lib/python3.9/site-packages/nvdiffrast/torch/ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "/home/jiyouseo/anaconda3/envs/dmodel/lib/python3.9/site-packages/nvdiffrast/torch/ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "/home/jiyouseo/anaconda3/envs/dmodel/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "/home/jiyouseo/anaconda3/envs/dmodel/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/jiyouseo/anaconda3/envs/dmodel/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1537, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/jiyouseo/anaconda3/envs/dmodel/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1825, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/1] c++ common.o glutil.o rasterize_gl.o torch_bindings_gl.o torch_rasterize_gl.o -shared -lGL -lEGL -L/home/jiyouseo/anaconda3/envs/dmodel/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/usr/local/cuda-11.3/lib64 -lcudart -o nvdiffrast_plugin_gl.so
FAILED: nvdiffrast_plugin_gl.so 
c++ common.o glutil.o rasterize_gl.o torch_bindings_gl.o torch_rasterize_gl.o -shared -lGL -lEGL -L/home/jiyouseo/anaconda3/envs/dmodel/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/usr/local/cuda-11.3/lib64 -lcudart -o nvdiffrast_plugin_gl.so
/usr/bin/ld: cannot find -lGL
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
~~~
So, I modify ['ninja', '-v'] to ['ninja', '--version'] in cpp_extension.py
Then It return 
~~~
ImportError:/home/jiyouseo/.cache/torch_extensions/py36_cu113/nvdiffrast_plugin_gl/nvdiffrast_plugin_gl.so: cannot open shared object file: No such file or directory
~~~
I guess it is because it cannot build nvdiffrast_plugin_gl.so.
How can I build exactly nvdiffrast_plugin_gl.so?
And this is my code environment.
~~~
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
~~~
~~~
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:3B:00.0 Off |                  Off |
| 58%   82C    P2   232W / 300W |  34285MiB / 48685MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    On   | 00000000:5E:00.0 Off |                  Off |
| 67%   85C    P2   234W / 300W |  33903MiB / 48685MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA RTX A6000    On   | 00000000:AF:00.0 Off |                  Off |
| 67%   85C    P2   235W / 300W |  34135MiB / 48685MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA RTX A6000    On   | 00000000:D8:00.0 Off |                  Off |
| 61%   84C    P2   232W / 300W |  34101MiB / 48685MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1733      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A     16354      C   ...onda/envs/uvtr/bin/python    34277MiB |
|    1   N/A  N/A      1733      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A     16355      C   ...onda/envs/uvtr/bin/python    33895MiB |
|    2   N/A  N/A      1733      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A     16356      C   ...onda/envs/uvtr/bin/python    34127MiB |
|    3   N/A  N/A      1733      G   /usr/lib/xorg/Xorg                  4MiB |
|    3   N/A  N/A     16357      C   ...onda/envs/uvtr/bin/python    34093MiB |
+-----------------------------------------------------------------------------+
~~~
Thank you.

**Comment by jmunkberg** [comment]
I was about to recommend that you file an issue in the nvdiffrast repo, but just found this issue https://github.com/NVlabs/nvdiffrast/issues/92

Closing this.
