### ISSUE TITLE
RuntimeError: OpenGL 4.4 or later is required

### ISSUE THREAD

**Issue by sadexcavator** [NVlabs/nvdiffrec#96]
hello, I recently had to move to a new server and I got this new problem, here's my log.
Config / Flags:
---------
config configs/bob.json
iter 500
batch 4
spp 1
layers 1
train_res [512, 512]
display_res [512, 512]
texture_res [1024, 1024]
display_interval 0
save_interval 100
learning_rate [0.03, 0.003]
min_roughness 0.08
custom_mip False
random_textures True
background white
loss logl1
out_dir out/bob
ref_mesh data/bob/bob_tri.obj
base_mesh None
validate False
mtl_override None
dmtet_grid 64
mesh_scale 2.1
env_scale 2.0
envmap data/irrmaps/aerodynamics_workshop_2k.hdr
display None
camera_space_light False
lock_light False
lock_pos False
sdf_regularizer 0.2
laplace relative
laplace_scale 10000.0
pre_load True
kd_min [0.0, 0.0, 0.0, 0.0]
kd_max [1.0, 1.0, 1.0, 1.0]
ks_min [0, 0.25, 0]
ks_max [1.0, 1.0, 1.0]
nrm_min [-1.0, -1.0, 0.0]
nrm_max [1.0, 1.0, 1.0]
cam_near_far [0.1, 1000.0]
learn_light True
local_rank 0
multi_gpu False
---------
Traceback (most recent call last):
  File "/home/wsr/workspace/nvdiffrec-main/train.py", line 557, in <module>
    glctx = dr.RasterizeGLContext()
  File "/home/wsr/anaconda3/envs/dmodel/lib/python3.9/site-packages/nvdiffrast/torch/ops.py", line 160, in __init__
    self.cpp_wrapper = _get_plugin().RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
RuntimeError: OpenGL 4.4 or later is required

could you tell me how to fix this? thanks a lot!

**Comment by jmunkberg** [comment]
Hello, 

This is an nvdiffrast issue, as that libvrary requires OpenGL to rasterize. Please see their docs for details. 

That said, they recently added a CUDA raster backend, as described here
https://nvlabs.github.io/nvdiffrast/#rasterizing-with-cuda-vs-opengl-new

You can test that if you want, to avoid the OpenGL requirement, but we haven't tested it locally, and cannot give support on that code path.

**Comment by sadexcavator** [comment]
For those who've met the same problem, if you want to fix this without installing the OpenGL, change line 557 in train.py to 'glctx = dr.RasterizeCudaContext()' and it will work. For the details of this, check the link jmunkberg gived above.
